"""Script export (pytest / CAPL) and spec-based coverage metrics for approved test cases."""
from __future__ import annotations

from .engine import parse_hex
from .spec import Spec


def _clean(text: str) -> str:
    return text.replace('"', "'").replace("\\", "/")


def to_python(cases: list) -> str:
    rows = "\n".join(
        f'    ("{c["id"]}", {{"session": {c["pre"]["session"]}, "unlocked": {c["pre"]["unlocked"]}, '
        f'"seed_issued": {c["pre"]["seed_issued"]}}}, "{c["request"]}", "{c["expected"]}"),  # {_clean(c["title"])}'
        for c in cases
    )
    return f'''"""Generated by UDS Diagnostics Assistant. Approved test cases only: review before use."""
import pytest

from ecu_client import EcuClient  # your transport wrapper: setup(**pre) and request(bytes) -> bytes

CASES = [
{rows}
]


@pytest.mark.parametrize("test_id, pre, request_hex, expected_hex", CASES)
def test_uds(test_id, pre, request_hex, expected_hex):
    ecu = EcuClient()
    ecu.setup(**pre)
    response = ecu.request(bytes.fromhex(request_hex))
    assert response.hex(" ").upper() == expected_hex, test_id
'''


def to_capl(cases: list) -> str:
    body = "\n".join(
        f'''testcase {c["id"].replace("-", "_")} ()
{{
  testCaseTitle("{c["id"]}", "{_clean(c["title"])}");
  Pre_Setup({c["pre"]["session"]}, {int(c["pre"]["unlocked"])}, {int(c["pre"]["seed_issued"])});
  if (SendRaw("{c["request"]}", "{c["expected"]}") != 1)
    testStepFail("{c["id"]}", "{_clean(c["criteria"])}");
  else
    testStepPass("{c["id"]}", "Response matches expectation");
}}
'''
        for c in cases
    )
    return ('/*@!Encoding:1252*/\n/* Generated by UDS Diagnostics Assistant. Approved test cases only: review before use. */\n'
            '/* Pre_Setup() and SendRaw() are provided by your CANoe test template. */\nincludes\n{\n}\n\n' + body)


def coverage(spec: Spec, approved: list, total: int) -> dict:
    sids = {c["sid"] for c in approved} & set(spec.services)
    nrcs = {parse_hex(c["expected"])[2] for c in approved if c["expected"].startswith("7F")} & set(spec.nrcs)
    sessions = {c["pre"]["session"] for c in approved} & set(spec.sessions)
    fmt = lambda xs: [f"{x:02X}" for x in sorted(xs)]
    return {
        "approved": len(approved), "total": total,
        "services": {"covered": len(sids), "total": len(spec.services), "missing": fmt(set(spec.services) - sids)},
        "nrcs": {"covered": len(nrcs), "total": len(spec.nrcs), "missing": fmt(set(spec.nrcs) - nrcs)},
        "sessions": {"covered": len(sessions), "total": len(spec.sessions), "missing": fmt(set(spec.sessions) - sessions)},
    }
